server:
  port: 9090
---
code:
  secret: secret message
  bignumber: ${random.long}
  uuid: ${random.uuid}

---
mybatis:
  type-aliases-package: com.example.demo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: test_user
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#---
#spring:
#  profiles: learning
#  datasource:
#    url: jdbc:mysql://localhost:3306/test_db?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
#    username: test_user
#    password: test1234
